package:
  name: pytraj

source:
  git_tag: v0.1.1.5
  git_url: http://github.com/mdtools/pytraj

requirements:
  build:
    - python
    - cython

  run:
    - python

test:
  imports:
    - pytraj

about:
  home: http://github.com/mdtools/pytraj 
  license: BSD
