package:
  name: pytraj

source:
  git_tag: master
  git_url: http://github.com/pytraj/pytraj

requirements:
  build:
    - libnetcdf
    - python
    - cython
  run:
    - python
    - libcpptraj
    - libnetcdf

test:
  imports:
    - pytraj
about:
  home: http://github.com/pytraj/pytraj
  license: BSD
