{% set name = "pytraj-dev" %}
{% set version = os.getenv('VERSION', 'v1.1.10.dev') %}
{% set short_version = version[1:] %}
{% set cpptraj_version = '4.3.2.1' %}

package:
  name: {{ name }}
  version: !!str {{ short_version }}

requirements:
  build:
    - python
    - cython
    - libcpptraj-dev
    - libnetcdf
  run:
    - python
    - libcpptraj-dev
    - libnetcdf
    - numpy

test:
  commands:
    - python -c 'import pytraj as pt; pt.show_versions(); from pytraj.testing import get_remd_fn'

about:
  home: http://github.com/amber-md/pytraj
  license: GPL v3
  summary: Python API for cpptraj - a package for data analysis of MD simulations
