language: python

env:
  matrix:
    - PYTHON_VERSION=2.7 CPPTRAJ_ANACONDA=NO
    - PYTHON_VERSION=3.4 CPPTRAJ_ANACONDA=NO
    - PYTHON_VERSION=3.5 CPPTRAJ_ANACONDA=NO
    - PYTHON_VERSION=3.4 CPPTRAJ_ANACONDA=YES
  global:
    - secure: JLFg6mbavHoSfqApsTUnE39ZtrEuv76UUsBwMJy3b8lp1s6dBwmbmEBm9VYb4wttCSKOd3BcuRd4lo5+Oxp25tKvLLg86P0PE6/cjn7vz3RAQ/qQhbEBUEV0nJkuKMCFpQPu8LGPY2oiRyPr4OGwfWdLzgYolMAxWtS6cCqAyPk=

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - libz-dev
    - libbz2-dev
    - libnetcdf-dev

install:
    - source devtools/travis-ci/setup_env.sh
    - conda config --add channels https://conda.binstar.org/ambermd
    - python --version
    - source devtools/travis-ci/install_cpptraj.sh
    - conda build --py $PYTHON_VERSION devtools/conda-recipe/pytraj
    - conda install $HOME/miniconda/conda-bld/linux-64/pytraj-dev-* --yes

script:
    - git clone https://github.com/Amber-MD/cpptraj
    - export PYTRAJHOME=`pwd`
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - conda install mpi4py libnetcdf --yes
    # conda seems weird. Why do we need to reinstall again?
    - conda install lapackamber arpack blasamber --yes -c ambermd
    - cd ./tests
    - python ./run_simple_test.py
    - python ./run_all_and_find_fails.py
    - cd ../examples
    - python ./run_all_and_find_fails.py
    - cd mpi_examples
    - sh run_all.sh 4 
    - cd $PYTRAJHOME

after_success:
    - echo "after_success"
    - source devtools/travis-ci/upload.sh 
    # just try to install
    - conda install -c ambermd pytraj-dev libcpptraj-dev --yes

notifications:
  email: false
