language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
before_install:
    - sudo apt-get install libnetcdf-dev
    - sudo apt-get install gfortran
    - sudo apt-get install -qq libz-dev libbz2-dev
    - sh ./devtools/for_travis/install_cpptraj.sh
install:
    - pip install --upgrade pip
    - pip install numpy
    - pip install cython
    - export AMBERHOME=`pwd`"/cpptraj/"
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - python ./setup.py install
script:
    - export AMBERHOME=`pwd`"/cpptraj/"
    - export PYCPPTRAJ_HOME=`pwd`
    - export LD_LIBRARY_PATH=$AMBERHOME/lib:$LD_LIBRARY_PATH
    - python ./development/for_travis/fake_test.py
    - python ./tests/test_import_class.py
    - cd ./tests
    - python -c 'import pytraj'
    - python ./API_test.py
    - python ./run_all_and_find_fails.py
    - sh ./TestListTravis.sh
    - cd ../examples
    - python ./run_all_and_find_fails.py
    - echo "Kool"

notifications:
  email: false
