language: python
env:
    matrix:
        - PYTHON_VERSION=3.4 
        - PYTHON_VERSION=3.3
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - libz-dev
      - libbz2-dev
      - libnetcdf-dev

install:
    - source devtools/travis-ci/setup_env.sh 
    #- python ./setup.py install

script:
    - conda config --add channels https://conda.binstar.org/pytraj
    - conda build devtools/conda-recipe/pytraj
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - export LD_LIBRARY_PATH=$CPPTRAJHOME/lib:$LD_LIBRARY_PATH
    - cd ./tests
    - python -c 'import pytraj'
    - python ./run_simple_test.py
    - python ./run_all_and_find_fails.py
    - python ./test_memory_accumulation.py
    - cd ../examples
    - python ./run_all_and_find_fails.py

notifications:
  email: false
