language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
before_install:
    - sudo apt-get install libnetcdf-dev
    - sudo apt-get install gfortran
    - sudo apt-get install -qq libz-dev libbz2-dev
    - sh ./for_travis/install_cpptraj.sh
    - sh ./for_travis/install_cython_git.sh
install:
    - pip install numpy
    - pip install memory_profiler
    - pip install line_profiler
    - export AMBERHOME=`pwd`"/Ambertools/V15.22b/cpptraj/"
    - export CPPTRAJHOME=`pwd`"/Ambertools/V15.22b/cpptraj/"
    - python ./setup.py install
script:
    - export AMBERHOME=`pwd`"/Ambertools/V15.22b/cpptraj/"
    - export PYCPPTRAJ_HOME=`pwd`
    - export LD_LIBRARY_PATH=$AMBERHOME/lib:$LD_LIBRARY_PATH
    - python ./for_travis/fake_test.py
    - python ./tests/test_import_class.py
    - cd ./tests
    - python -c 'import pytraj'
    - python ./API_test.py
    - python RunAllAndFindFailure.py
    - sh ./TestListTravis.sh
    - cd ../examples
    - sh ./TestList.sh
    - echo "Kool"

notifications:
  email: false
