language: python

env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.4
  global:
    - secure: JLFg6mbavHoSfqApsTUnE39ZtrEuv76UUsBwMJy3b8lp1s6dBwmbmEBm9VYb4wttCSKOd3BcuRd4lo5+Oxp25tKvLLg86P0PE6/cjn7vz3RAQ/qQhbEBUEV0nJkuKMCFpQPu8LGPY2oiRyPr4OGwfWdLzgYolMAxWtS6cCqAyPk=

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - libz-dev
    - libbz2-dev
    - libblas-dev
    - liblapack-dev
    - libarpack2-dev
    - libnetcdf-dev

install:
    - source devtools/travis-ci/setup_env.sh
    - python --version

script:
    - export PYTRAJHOME=`pwd`
    - python setup.py install
    - export LD_LIBRARY_PATH=`pwd`"/cpptraj/lib":$LD_LIBRARY_PATH
    - cd ./tests
    - python ./run_simple_test.py
    - python ./run_full_tests.py
    #- nosetests --with-coverage --cover-package pytraj -vs test_*.py */test_*.py
    - cd ../examples
    - python ./run_examples.py
    - cd mpi_examples
    - sh run_mpi_examples.sh 4 
    - cd $PYTRAJHOME

after_success:
    - echo "after_success"
    - coveralls

notifications:
  email: false
