language: python
env:
  secure: JLFg6mbavHoSfqApsTUnE39ZtrEuv76UUsBwMJy3b8lp1s6dBwmbmEBm9VYb4wttCSKOd3BcuRd4lo5+Oxp25tKvLLg86P0PE6/cjn7vz3RAQ/qQhbEBUEV0nJkuKMCFpQPu8LGPY2oiRyPr4OGwfWdLzgYolMAxWtS6cCqAyPk=
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - libz-dev
    - libbz2-dev
    - libnetcdf-dev
install:
- source 0.sh
- source devtools/travis-ci/setup_env.sh
- conda config --add channels https://conda.binstar.org/ambermd
- conda config --add channels https://conda.binstar.org/pytraj
- python --version
- conda build --py $PYTHON_VERSION devtools/conda-recipe/pytraj
- conda install $HOME/miniconda/conda-bld/linux-64/pytraj-dev-* --yes
script:
- git clone https://github.com/Amber-MD/cpptraj
- export CPPTRAJHOME=`pwd`"/cpptraj/"
- conda install libcpptraj -c pytraj --force --yes
- conda install libnetcdf --yes
after_success:
- echo "after_success"
- source devtools/travis-ci/upload.sh
notifications:
  email: false
