language: python
env:
    matrix:
        - PYTHON_VERSION=2.7 
        - PYTHON_VERSION=2.7 NO_CYTHON=yes
        - PYTHON_VERSION=3.4 
        - PYTHON_VERSION=3.4 NO_CYTHON=yes

before_install:
    - sudo apt-get install libnetcdf-dev
    - sudo apt-get install gfortran
    - sudo apt-get install -qq libz-dev libbz2-dev
    - pip install git+git://github.com/swails/ParmEd
    - sh ./devtools/for_travis/install_cpptraj.sh

install:
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - source devtools/for_travis/setup_env.sh 
    - python ./setup.py install

script:
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - export LD_LIBRARY_PATH=$CPPTRAJHOME/lib:$LD_LIBRARY_PATH
    - cd ./tests
    - python -c 'import pytraj'
    - python ./run_simple_test.py
    - python ./run_all_and_find_fails.py
    - cd ../examples
    - python ./run_all_and_find_fails.py

notifications:
  email: false
