language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
before_install:
    - sudo apt-get install libnetcdf-dev
    - sudo apt-get install gfortran
    - sudo apt-get install -qq libz-dev libbz2-dev
    - sh ./devtools/for_travis/install_cpptraj.sh
install:
    - pip install --upgrade pip
    - pip install numpy
    - pip install cython
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - python ./scripts/setup_faster_build.py build
    - python ./setup.py install
script:
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - export LD_LIBRARY_PATH=$CPPTRAJHOME/lib:$LD_LIBRARY_PATH
    - cd ./tests
    - python -c 'import pytraj'
    - python ./run_simple_test.py
    - python ./run_all_and_find_fails.py
    - sh ./TestListTravis.sh
    - cd ../examples
    - python ./run_all_and_find_fails.py
    - cd ../tests
    - grep File log | grep test
    - echo "Kool"

notifications:
  email: false
