language: cpp

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=2.7 }
    # - { os: linux, env: PYTHON_VERSION=3.4 }
    # - { os: linux, env: PYTHON_VERSION=3.5 }
    - { os: osx, env: PYTHON_VERSION=2.7 }

sudo: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science;
      brew update;
      brew install netcdf fftw;
    fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - clang
    - libz-dev
    - libbz2-dev
    - libblas-dev
    - liblapack-dev
    - libarpack2-dev
    - libnetcdf-dev

install:
    - source devtools/travis-ci/setup_env.sh
    - python --version

script:
    - source devtools/travis-ci/install_pytraj.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export LD_LIBRARY_PATH=`pwd`"/cpptraj/lib":$LD_LIBRARY_PATH;
      else
        export LD_LIBRARY_PATH=`pwd`"/cpptraj/lib":$LD_LIBRARY_PATH;
      fi
    - sh ./devtools/travis-ci/pyflakes_check.sh
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - ls $CPPTRAJHOME/lib/
    - export DYLD_LIBRARY_PATH=$CPPTRAJHOME/lib/
    - otool -L /Users/travis/miniconda/envs/myenv/lib/python2.7/site-packages/pytraj/cpp_options.so
    # - sudo ln -s $CPPTRAJHOME/lib/libcpptraj.dylib /usr/local/lib/libcpptraj.dylib
    - cd ./tests
    - python -c 'import pytraj as pt'
    - python ./run_simple_test.py
    - nosetests --with-coverage --cover-package pytraj -vs test_*.py */test_*.py
    - unset CPPTRAJHOME # for pytraj.tools coverage
    - nosetests --with-coverage --cover-package pytraj -vs test_docs.py
    - cd ../examples
    - python ./run_examples.py
    - cd mpi_examples
    - sh run_mpi_examples.sh 4 

after_success:
    - echo "after_success"
    - cd ../../tests/
    - ../devtools/travis-ci/coveralls

notifications:
  email: false
