language: python
env:
    matrix:
        - PYTHON_VERSION=3.4 
        - PYTHON_VERSION=2.7

before_install:
    - sudo apt-get install libnetcdf-dev
    - sudo apt-get install gfortran
    - sudo apt-get install -qq libz-dev libbz2-dev

install:
    - source devtools/travis-ci/setup_env.sh 
    - python ./setup.py install

script:
    - export CPPTRAJHOME=`pwd`"/cpptraj/"
    - export LD_LIBRARY_PATH=$CPPTRAJHOME/lib:$LD_LIBRARY_PATH
    - cd ./tests
    - python -c 'import pytraj'
    - python ./run_simple_test.py
    - python ./run_all_and_find_fails.py
    - python ./test_memory_accumulation.py
    - cd ../examples
    - python ./run_all_and_find_fails.py

notifications:
  email: false
