package:
  name: pytraj-dev
  version: !!str 0.1.2.dev0

source:
  fn: master.zip
  url: https://github.com/pytraj/pytraj/archive/master.zip

requirements:
  build:
    - python
    - cython
    - libcpptraj
  run:
    - python
    - libcpptraj
    - matplotlib
    - numpy

about:
  home: http://github.com/pytraj/pytraj
  license: BSD
  summary: Python wrapper for cpptraj - a package for data analysis of MD simulations
