package:
  name: libcpptraj
  version: 4.2.0

source:
  git_tag: master
  git_url: http://github.com/mojyt/cpptraj/

about:
    home: http://ambermd.org/
    license: GNU
    summary: libcpptraj for pytraj
