package:
  name: libcpptraj
  version: 4.2.0

source:
  git_tag: master
  git_url: http://github.com/mojyt/cpptraj/

requirements:
  build:
    - libnetcdf

about:
    home: http://ambermd.org/
    license: GNU
    summary: libcpptraj for pytraj
