package:
  name: pytraj

source:
  git_tag: pytraj.v0.1.beta
  git_url: http://github.com/pytraj/pytraj

requirements:
  build:
    - python
    - cython

  run:
    - python

test:
  imports:
    - pytraj

about:
  home: http://github.com/pytraj/pytraj
  license: BSD
